FROM python:3.11-slim

WORKDIR /app/dashboard

RUN pip install --upgrade pip setuptools wheel

COPY /dashboard /app/dashboard

RUN pip install -e /app/dashboard

EXPOSE 8501

CMD ["streamlit", "run", "Startsida.py", "--server.port=8501", "--server.address=0.0.0.0"]