version: "3.9"

services:
  dwh_thepipe:
    platform: linux/amd64
    build:
      context: .
      dockerfile: dockerfile.dwh
    ports:
      - "3000:3000"
    image: crmarcusjohn.azurecr.io/hr_daily_dashboard:latest